--- #YAML:1.0
name:               Acme-Mahjong-Rule-CC
version:            0.21
abstract:           Exchange Tables for a Classic Chinese Version of Mahjong.
author:
    - Caleb Veenstra <cjveenst@mtu.edu>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:  {}
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
